docType = "CompanyManLink"
tableComment = "связь компании и человека"

tableName ="company_man_link"

fields = [
	{name="id",			type="serial"},
	{name="company_id",					type="int",	 comment="компания"},
	{name="man_id",					type="int",	 comment="человек"},
	{name="description",					type="text",	 comment="описание"},
	{name="author_id",					type="int",	 comment="автор"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{fld="company_id", ref="task", fk="id"},
	{fld="man_id", ref="man", fk="id"},
	{fld="author_id", ref="man", fk="id"},
	{name="company_man_link_already_exist", ext="UNIQUE (company_id, man_id)"},
]

triggers = [
	{name="company_man_link_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="company_man_link_trigger_before", when="before insert or update", ref="for each row", funcName="company_man_link_trigger_before"},
	{name="company_man_link_trigger_after", when="after insert or update", ref="for each row", funcName="company_man_link_trigger_after"}
]



methods = [
	"company_man_link_get_by_id",
	"company_man_link_list",
	"company_man_link_update",
	"company_man_link_trigger_before",
	"company_man_link_trigger_after"
]

alterScripts = [
	"alter table company_man_link add column if not exists company_id int;",
	"alter table company_man_link add column if not exists man_id int;",
	"alter table company_man_link add column if not exists description text;",
	"alter table company_man_link add column if not exists author_id int;",
	"alter table company_man_link add column if not exists search_text text;"
]