docType = "CtlgFunctionalRequirementState"
tableComment = "статус функциональности"

tableName ="ctlg_functional_requirement_state"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="ctlg_functional_requirement_state_title_already_exist", ext="UNIQUE (title)"}
]

triggers = [
	{name="ctlg_functional_requirement_state_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="ctlg_functional_requirement_state_trigger_before", when="before insert or update", ref="for each row", funcName="ctlg_functional_requirement_state_trigger_before"},
	{name="ctlg_functional_requirement_state_trigger_after", when="after insert or update", ref="for each row", funcName="ctlg_functional_requirement_state_trigger_after"}
]



methods = [
	"ctlg_functional_requirement_state_get_by_id",
	"ctlg_functional_requirement_state_list",
	"ctlg_functional_requirement_state_update",
	"ctlg_functional_requirement_state_trigger_before",
	"ctlg_functional_requirement_state_trigger_after"
]

alterScripts = [
	"alter table ctlg_functional_requirement_state add column if not exists title CHARACTER VARYING(150);",
	"alter table ctlg_functional_requirement_state add column if not exists search_text text;"
]