docType = "Sprint"
tableComment = "спринт"

tableName ="sprint"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="sprint_title_already_exist", ext="UNIQUE (title)"}
]

triggers = [
	{name="sprint_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="sprint_trigger_before", when="before insert or update", ref="for each row", funcName="sprint_trigger_before"},
	{name="sprint_trigger_after", when="after insert or update", ref="for each row", funcName="sprint_trigger_after"}
]



methods = [
	"sprint_update",
	"sprint_get_by_id",
	"sprint_list",
	"sprint_trigger_before",
	"sprint_trigger_after"
]

alterScripts = [
	"alter table sprint add column if not exists title CHARACTER VARYING(150);",
	"alter table sprint add column if not exists search_text text;"
]