docType = "Man"
tableComment = "контакт"

tableName ="man"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="text",	 comment="название"},
	{name="last_name",					type="char",	size=30,	 comment="фамилия"},
	{name="first_name",					type="char",	size=30,	 comment="имя"},
	{name="middle_name",					type="char",	size=30,	 comment="отчество"},
	{name="company_id",					type="int",	 comment="компания"},
	{name="position",					type="char",	size=50,	 comment="должность"},
	{name="user_table_id",					type="int",	 comment="пользователь"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{fld="company_id", ref="company", fk="id"},
{fld="user_table_id", ref="\"user\"", fk="id"}
]

triggers = [
	{name="man_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="man_trigger_before", when="before insert or update", ref="for each row", funcName="man_trigger_before"},
	{name="man_trigger_after", when="after insert or update", ref="for each row", funcName="man_trigger_after"}
]



methods = [
	"man_list",
	"man_update",
	"man_get_by_id",
	"man_trigger_before",
	"man_trigger_after"
]

alterScripts = [
	"alter table man add column if not exists title text;",
	"alter table man add column if not exists last_name CHARACTER VARYING(30);",
	"alter table man add column if not exists first_name CHARACTER VARYING(30);",
	"alter table man add column if not exists middle_name CHARACTER VARYING(30);",
	"alter table man add column if not exists company_id int;",
	"alter table man add column if not exists position CHARACTER VARYING(50);",
	"alter table man add column if not exists user_table_id int;",
	"alter table man add column if not exists search_text text;"
]