docType = "CustomerTask"
tableComment = "задача заказчика"

tableName ="customer_task"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="state_id",					type="int", 	ext=" default 1",	 comment="статус"},
	{name="digital_solution_id",					type="int",	 comment="цифровое решение"},
	{name="company_id",					type="int",	 comment="компания"},
	{name="description",					type="text",	 comment="описание"},
	{name="files",					type="jsonb",	 comment="файлы"},
	{name="images",					type="jsonb",	 comment="изображения"},
	{name="author_id",					type="int",	 comment="автор"},
	{name="plan_start_date",					type="timestamp",	 comment="плановая дата начала"},
	{name="fact_start_date",					type="timestamp",	 comment="фактическая дата начала"},
	{name="plan_end_date",					type="timestamp",	 comment="плановая дата завершения"},
	{name="fact_end_date",					type="timestamp",	 comment="фактическая дата завершения"},
	{name="result",					type="text",	 comment="результат"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="customer_task_title_already_exist", ext="UNIQUE (title)"},
	{fld="state_id", ref="ctlg_customer_task_state", fk="id"},
	{fld="digital_solution_id", ref="digital_solution", fk="id"},
	{fld="company_id", ref="company", fk="id"},
	{fld="author_id", ref="man", fk="id"}
]

triggers = [
	{name="customer_task_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="customer_task_trigger_before", when="before insert or update", ref="for each row", funcName="customer_task_trigger_before"},
	{name="customer_task_trigger_after", when="after insert or update", ref="for each row", funcName="customer_task_trigger_after"}
]



methods = [
	"customer_task_get_by_id",
	"customer_task_list",
	"customer_task_update",
	"customer_task_trigger_before",
	"customer_task_trigger_after"
]

alterScripts = [
	"alter table customer_task add column if not exists title CHARACTER VARYING(150);",
	"alter table customer_task add column if not exists state_id int;",
	"alter table customer_task add column if not exists digital_solution_id int;",
	"alter table customer_task add column if not exists company_id int;",
	"alter table customer_task add column if not exists description text;",
	"alter table customer_task add column if not exists files jsonb;",
	"alter table customer_task add column if not exists images jsonb;",
	"alter table customer_task add column if not exists author_id int;",
	"alter table customer_task add column if not exists plan_start_date timestamp;",
	"alter table customer_task add column if not exists fact_start_date timestamp;",
	"alter table customer_task add column if not exists plan_end_date timestamp;",
	"alter table customer_task add column if not exists fact_end_date timestamp;",
	"alter table customer_task add column if not exists result text;",
	"alter table customer_task add column if not exists search_text text;"
]