docType = "TechnicalTask"
tableComment = "техническое задание"

tableName ="technical_task"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="state_id",					type="int", 	ext=" default 1",	 comment="статус документа"},
	{name="work_state_id",					type="int", 	ext=" default 1",	 comment="статус работ по ТЗ"},
	{name="contract_id",					type="int",	 comment="договор"},
	{name="amount",					type="int",	 comment="сумма"},
	{name="date",					type="timestamp",	 comment="дата подписания ТЗ"},
	{name="description",					type="text",	 comment="описание"},
	{name="document",					type="jsonb",	 comment="документ"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="technical_task_title_already_exist", ext="UNIQUE (title)"},
	{fld="state_id", ref="ctlg_technical_task_state", fk="id"},
	{fld="work_state_id", ref="ctlg_technical_task_work_state", fk="id"},
	{fld="contract_id", ref="contract", fk="id"}
]

triggers = [
	{name="technical_task_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="technical_task_trigger_before", when="before insert or update", ref="for each row", funcName="technical_task_trigger_before"},
	{name="technical_task_trigger_after", when="after insert or update", ref="for each row", funcName="technical_task_trigger_after"}
]



methods = [
	"technical_task_get_by_id",
	"technical_task_list",
	"technical_task_update",
	"technical_task_trigger_before",
	"technical_task_trigger_after"
]

alterScripts = [
	"alter table technical_task add column if not exists title CHARACTER VARYING(150);",
	"alter table technical_task add column if not exists state_id int;",
	"alter table technical_task add column if not exists work_state_id int;",
	"alter table technical_task add column if not exists contract_id int;",
	"alter table technical_task add column if not exists amount int;",
	"alter table technical_task add column if not exists date timestamp;",
	"alter table technical_task add column if not exists description text;",
	"alter table technical_task add column if not exists document jsonb;",
	"alter table technical_task add column if not exists search_text text;"
]