docType = "Comment"
tableComment = "комментарий"

tableName ="comment"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="comment_title_already_exist", ext="UNIQUE (title)"}
]

triggers = [
	{name="comment_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="comment_trigger_before", when="before insert or update", ref="for each row", funcName="comment_trigger_before"},
	{name="comment_trigger_after", when="after insert or update", ref="for each row", funcName="comment_trigger_after"}
]



methods = [
	"comment_get_by_id",
	"comment_list",
	"comment_update",
	"comment_trigger_before",
	"comment_trigger_after"
]

alterScripts = [
	"alter table comment add column if not exists title CHARACTER VARYING(150);",
	"alter table comment add column if not exists search_text text;"
]