docType = "DigitalSolutionSpecialistLink"
tableComment = "связь цифрового решения и специалиста"

tableName ="digital_solution_specialist_link"

fields = [
	{name="id",			type="serial"},
	{name="digital_solution_id",					type="int",	 comment="id цифрового решения"},
	{name="specialist_id",					type="int",	 comment="специалист"},
	{name="role_id",					type="int",	 comment="роль"},
	{name="description",					type="text",	 comment="описание"},
	{name="author_id",					type="int",	 comment="автор"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{fld="digital_solution_id", ref="digital_solution", fk="id"},
	{fld="specialist_id", ref="man", fk="id"},
	{fld="role_id", ref="ctlg_digital_solution_specialist_role", fk="id"},
	{fld="author_id", ref="man", fk="id"},
	{name="digital_solution_specialist_link_already_exist", ext="UNIQUE (digital_solution_id, specialist_id)"},
]

triggers = [
	{name="digital_solution_specialist_link_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="digital_solution_specialist_link_trigger_before", when="before insert or update", ref="for each row", funcName="digital_solution_specialist_link_trigger_before"},
	{name="digital_solution_specialist_link_trigger_after", when="after insert or update", ref="for each row", funcName="digital_solution_specialist_link_trigger_after"}
]



methods = [
	"digital_solution_specialist_link_list",
	"digital_solution_specialist_link_update",
	"digital_solution_specialist_link_get_by_id",
	"digital_solution_specialist_link_trigger_before",
	"digital_solution_specialist_link_trigger_after"
]

alterScripts = [
	"alter table digital_solution_specialist_link add column if not exists digital_solution_id int;",
	"alter table digital_solution_specialist_link add column if not exists specialist_id int;",
	"alter table digital_solution_specialist_link add column if not exists role_id int;",
	"alter table digital_solution_specialist_link add column if not exists description text;",
	"alter table digital_solution_specialist_link add column if not exists author_id int;",
	"alter table digital_solution_specialist_link add column if not exists search_text text;"
]