docType = "System"
tableComment = "система"

tableName ="system"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="state",					type="char",	size=50,	 comment="статус"},
	{name="description",					type="text",	 comment="описание"},
	{name="files",					type="jsonb",	 comment="файлы"},
	{name="images",					type="jsonb",	 comment="изображения"},
	{name="customer_id",					type="int",	 comment="заказчик"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="system_title_already_exist", ext="UNIQUE (title)"},
	{fld="customer_id", ref="company", fk="id"}
]

triggers = [
	{name="system_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="system_trigger_before", when="before insert or update", ref="for each row", funcName="system_trigger_before"},
	{name="system_trigger_after", when="after insert or update", ref="for each row", funcName="system_trigger_after"}
]



methods = [
	"system_list",
	"system_update",
	"system_get_by_id",
	"system_trigger_before",
	"system_trigger_after"
]

alterScripts = [
	"alter table system add column if not exists title CHARACTER VARYING(150);",
	"alter table system add column if not exists state CHARACTER VARYING(50);",
	"alter table system add column if not exists description text;",
	"alter table system add column if not exists files jsonb;",
	"alter table system add column if not exists images jsonb;",
	"alter table system add column if not exists customer_id int;",
	"alter table system add column if not exists search_text text;"
]