docType = "Payment"
tableComment = "платёж"

tableName ="payment"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="amount",					type="int",	 comment="размер платежа"},
	{name="payment_date",					type="timestamp",	 comment="дата платежа"},
	{name="payment_receipt_date",					type="timestamp",	 comment="дата поступления платежа"},
	{name="invoice_id",					type="int",	 comment="счёт"},
	{name="payment_order",					type="jsonb",	 comment="платёжное поручение"},
	{name="description",					type="text",	 comment="описание"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="payment_title_already_exist", ext="UNIQUE (title)"},
	{fld="invoice_id", ref="invoice", fk="id"}
]

triggers = [
	{name="payment_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="payment_trigger_before", when="before insert or update", ref="for each row", funcName="payment_trigger_before"},
	{name="payment_trigger_after", when="after insert or update", ref="for each row", funcName="payment_trigger_after"}
]



methods = [
	"payment_get_by_id",
	"payment_list",
	"payment_update",
	"payment_trigger_before",
	"payment_trigger_after"
]

alterScripts = [
	"alter table payment add column if not exists title CHARACTER VARYING(150);",
	"alter table payment add column if not exists amount int;",
	"alter table payment add column if not exists payment_date timestamp;",
	"alter table payment add column if not exists payment_receipt_date timestamp;",
	"alter table payment add column if not exists invoice_id int;",
	"alter table payment add column if not exists payment_order jsonb;",
	"alter table payment add column if not exists description text;",
	"alter table payment add column if not exists search_text text;"
]