docType = "Task"
tableComment = "задача"

tableName ="task"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="type_id",					type="int",	 comment="тип задачи"},
	{name="stage_id",					type="int", 	ext="not null default 1",	 comment="этап"},
	{name="state_id",					type="int", 	ext="not null default 1",	 comment="статус"},
	{name="system_id",					type="int", 	ext="not null",	 comment="система"},
	{name="plan_end_date",					type="timestamp",	 comment="плановая дата завершения"},
	{name="fact_end_date",					type="timestamp",	 comment="фактическая дата завершения"},
	{name="customer_priority",					type="int",	 comment="приоритет заказчика"},
	{name="estimate",					type="int",	 comment="оценка"},
	{name="worked_time",					type="int",	 comment="затрачено"},
	{name="description",					type="text",	 comment="описание"},
	{name="description_files",					type="jsonb",	 comment="файлы"},
	{name="description_images",					type="jsonb",	 comment="изображения"},
	{name="how_to_check",					type="text",	 comment="как проверить задачу"},
	{name="how_to_check_files",					type="jsonb",	 comment="файлы"},
	{name="how_to_check_images",					type="jsonb",	 comment="изображения"},
	{name="result",					type="text",	 comment="результат"},
	{name="result_files",					type="jsonb",	 comment="файлы результата"},
	{name="result_images",					type="jsonb",	 comment="изображения результата"},
	{name="history",					type="jsonb",	 comment="история"},
	{name="executor_responsible_id",					type="int",	 comment="ответственный исполнитель"},
	{name="customer_responsible_id",					type="int",	 comment="ответственный заказчик"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{fld="type_id", ref="ctlg_task_type", fk="id"},
	{fld="stage_id", ref="ctlg_task_stage", fk="id"},
	{fld="state_id", ref="ctlg_task_state", fk="id"},
	{fld="system_id", ref="system", fk="id"},
	{fld="executor_responsible_id", ref="contact", fk="id"},
	{fld="customer_responsible_id", ref="contact", fk="id"}
]

triggers = [
	{name="task_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="task_trigger_before", when="before insert or update", ref="for each row", funcName="task_trigger_before"},
	{name="task_trigger_after", when="after insert or update", ref="for each row", funcName="task_trigger_after"}
]



methods = [
	"task_to_done",
	"task_change_plan_end_date",
	"task_update",
	"task_to_backlog",
	"task_to_in_process",
	"task_to_internal_check",
	"task_to_customer_check",
	"task_save_history",
	"task_list",
	"task_get_by_id",
	"task_create",
	"task_trigger_before",
	"task_trigger_after"
]

alterScripts = [
	"alter table task add column if not exists title CHARACTER VARYING(150);",
	"alter table task add column if not exists type_id int;",
	"alter table task add column if not exists stage_id int;",
	"alter table task add column if not exists state_id int;",
	"alter table task add column if not exists system_id int;",
	"alter table task add column if not exists plan_end_date timestamp;",
	"alter table task add column if not exists fact_end_date timestamp;",
	"alter table task add column if not exists customer_priority int;",
	"alter table task add column if not exists estimate int;",
	"alter table task add column if not exists worked_time int;",
	"alter table task add column if not exists description text;",
	"alter table task add column if not exists description_files jsonb;",
	"alter table task add column if not exists description_images jsonb;",
	"alter table task add column if not exists how_to_check text;",
	"alter table task add column if not exists how_to_check_files jsonb;",
	"alter table task add column if not exists how_to_check_images jsonb;",
	"alter table task add column if not exists result text;",
	"alter table task add column if not exists result_files jsonb;",
	"alter table task add column if not exists result_images jsonb;",
	"alter table task add column if not exists history jsonb;",
	"alter table task add column if not exists executor_responsible_id int;",
	"alter table task add column if not exists customer_responsible_id int;",
	"alter table task add column if not exists search_text text;"
]