docType = "DevelopmentTask"
tableComment = "задача по разработке"

tableName ="development_task"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="type_id",					type="int",	 comment="тип"},
	{name="state_id",					type="int",	 comment="статус"},
	{name="digital_solution_id",					type="int",	 comment="цифровое решение"},
	{name="responsible_id",					type="int",	 comment="ответственный"},
	{name="sprint_id",					type="int",	 comment="спринт"},
	{name="estimate",					type="int",	 comment="оценка"},
	{name="internal_priority",					type="int",	 comment="приоритет"},
	{name="plan_end_date",					type="timestamp",	 comment="плановая дата завершения"},
	{name="fact_end_date",					type="timestamp",	 comment="фактическая дата завершения"},
	{name="description",					type="text",	 comment="описание"},
	{name="description_files",					type="jsonb",	 comment="файлы описания"},
	{name="description_images",					type="jsonb",	 comment="изображения описания"},
	{name="result",					type="text",	 comment="результат"},
	{name="result_files",					type="jsonb",	 comment="файлы результата"},
	{name="result_images",					type="jsonb",	 comment="изображения результата"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{fld="type_id", ref="ctlg_development_task_type", fk="id"},
	{fld="state_id", ref="ctlg_development_task_state", fk="id"},
	{fld="digital_solution_id", ref="digital_solution", fk="id"},
	{fld="responsible_id", ref="man", fk="id"},
	{fld="sprint_id", ref="sprint", fk="id"}
]

triggers = [
	{name="development_task_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="development_task_trigger_before", when="before insert or update", ref="for each row", funcName="development_task_trigger_before"},
	{name="development_task_trigger_after", when="after insert or update", ref="for each row", funcName="development_task_trigger_after"}
]



methods = [
	"development_task_list",
	"development_task_update",
	"development_task_get_by_id",
	"development_task_trigger_before",
	"development_task_trigger_after"
]

alterScripts = [
	"alter table development_task add column if not exists title CHARACTER VARYING(150);",
	"alter table development_task add column if not exists type_id int;",
	"alter table development_task add column if not exists state_id int;",
	"alter table development_task add column if not exists digital_solution_id int;",
	"alter table development_task add column if not exists responsible_id int;",
	"alter table development_task add column if not exists sprint_id int;",
	"alter table development_task add column if not exists estimate int;",
	"alter table development_task add column if not exists internal_priority int;",
	"alter table development_task add column if not exists plan_end_date timestamp;",
	"alter table development_task add column if not exists fact_end_date timestamp;",
	"alter table development_task add column if not exists description text;",
	"alter table development_task add column if not exists description_files jsonb;",
	"alter table development_task add column if not exists description_images jsonb;",
	"alter table development_task add column if not exists result text;",
	"alter table development_task add column if not exists result_files jsonb;",
	"alter table development_task add column if not exists result_images jsonb;",
	"alter table development_task add column if not exists search_text text;"
]