docType = "FunctionalRequirement"
tableComment = "функциональное требование"

tableName ="functional_requirement"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="state_id",					type="int", 	ext=" default 1",	 comment="статус"},
	{name="description",					type="text",	 comment="описание"},
	{name="request_id",					type="int",	 comment="запрос"},
	{name="digital_solution_id",					type="int",	 comment="цифровое решение"},
	{name="system_id",					type="int",	 comment="система"},
	{name="result",					type="text",	 comment="результат"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="functional_requirement_title_already_exist", ext="UNIQUE (title)"},
	{fld="state_id", ref="ctlg_functional_requirement_state", fk="id"},
	{fld="request_id", ref="request", fk="id"},
	{fld="digital_solution_id", ref="digital_solution", fk="id"},
	{fld="system_id", ref="system", fk="id"}
]

triggers = [
	{name="functional_requirement_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="functional_requirement_trigger_before", when="before insert or update", ref="for each row", funcName="functional_requirement_trigger_before"},
	{name="functional_requirement_trigger_after", when="after insert or update", ref="for each row", funcName="functional_requirement_trigger_after"}
]



methods = [
	"functional_requirement_update",
	"functional_requirement_get_by_id",
	"functional_requirement_list",
	"functional_requirement_trigger_before",
	"functional_requirement_trigger_after"
]

alterScripts = [
	"alter table functional_requirement add column if not exists title CHARACTER VARYING(150);",
	"alter table functional_requirement add column if not exists state_id int;",
	"alter table functional_requirement add column if not exists description text;",
	"alter table functional_requirement add column if not exists request_id int;",
	"alter table functional_requirement add column if not exists digital_solution_id int;",
	"alter table functional_requirement add column if not exists system_id int;",
	"alter table functional_requirement add column if not exists result text;",
	"alter table functional_requirement add column if not exists search_text text;"
]