docType = "CustomerTask"
tableComment = "задача заказчика"

tableName ="customer_task"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="state_id",					type="int", 	ext=" default 1",	 comment="статус"},
	{name="system_id",					type="int",	 comment="система"},
	{name="task_id",					type="int",	 comment="задача"},
	{name="responsible_id",					type="int",	 comment="ответственный"},
	{name="plan_end_date",					type="timestamp",	 comment="плановая дата завершения"},
	{name="fact_end_date",					type="timestamp",	 comment="фактическая дата завершения"},
	{name="description",					type="text",	 comment="описание"},
	{name="description_files",					type="jsonb",	 comment="файлы описания"},
	{name="description_images",					type="jsonb",	 comment="изображения описания"},
	{name="process",					type="text",	 comment="процесс"},
	{name="is_paused",					type="bool",	 comment="на паузе"},
	{name="process_files",					type="jsonb",	 comment="файлы результата"},
	{name="process_images",					type="jsonb",	 comment="изображения результата"},
	{name="result",					type="text",	 comment="результат"},
	{name="result_files",					type="jsonb",	 comment="файлы результата"},
	{name="result_images",					type="jsonb",	 comment="изображения результата"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="customer_task_title_already_exist", ext="UNIQUE (title)"},
	{fld="state_id", ref="ctlg_customer_task_state", fk="id"},
	{fld="system_id", ref="system", fk="id"},
	{fld="task_id", ref="task", fk="id"},
	{fld="responsible_id", ref="man", fk="id"}
]

triggers = [
	{name="customer_task_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="customer_task_trigger_before", when="before insert or update", ref="for each row", funcName="customer_task_trigger_before"},
	{name="customer_task_trigger_after", when="after insert or update", ref="for each row", funcName="customer_task_trigger_after"}
]



methods = [
	"customer_task_update",
	"customer_task_get_by_id",
	"customer_task_list",
	"customer_task_trigger_before",
	"customer_task_trigger_after"
]

alterScripts = [
	"alter table customer_task add column if not exists title CHARACTER VARYING(150);",
	"alter table customer_task add column if not exists state_id int;",
	"alter table customer_task add column if not exists system_id int;",
	"alter table customer_task add column if not exists task_id int;",
	"alter table customer_task add column if not exists responsible_id int;",
	"alter table customer_task add column if not exists plan_end_date timestamp;",
	"alter table customer_task add column if not exists fact_end_date timestamp;",
	"alter table customer_task add column if not exists description text;",
	"alter table customer_task add column if not exists description_files jsonb;",
	"alter table customer_task add column if not exists description_images jsonb;",
	"alter table customer_task add column if not exists process text;",
	"alter table customer_task add column if not exists is_paused bool;",
	"alter table customer_task add column if not exists process_files jsonb;",
	"alter table customer_task add column if not exists process_images jsonb;",
	"alter table customer_task add column if not exists result text;",
	"alter table customer_task add column if not exists result_files jsonb;",
	"alter table customer_task add column if not exists result_images jsonb;",
	"alter table customer_task add column if not exists search_text text;"
]