docType = "Request"
tableComment = "запрос"

tableName ="request"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="system_id",					type="int",	 comment="система"},
	{name="description",					type="text",	 comment="описание"},
	{name="state_id",					type="int",	 comment="статус"},
	{name="rsk_id",					type="int",	 comment="рск"},
	{name="datetime_reciept",					type="timestamp",	 comment="дата и время получения запроса"},
	{name="how_request_received",					type="text",	 comment="как получен запрос"},
	{name="customer_id",					type="int",	 comment="заказчик"},
	{name="customer_agent_id",					type="int",	 comment="представитель заказчика"},
	{name="demo_task_id",					type="text",	 comment="задачи"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="request_title_already_exist", ext="UNIQUE (title)"},
	{fld="system_id", ref="system", fk="id"},
	{fld="state_id", ref="ctlg_request_state", fk="id"},
	{fld="rsk_id", ref="man", fk="id"},
	{fld="customer_id", ref="company", fk="id"},
	{fld="customer_agent_id", ref="man", fk="id"}
]

triggers = [
	{name="request_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="request_trigger_before", when="before insert or update", ref="for each row", funcName="request_trigger_before"},
	{name="request_trigger_after", when="after insert or update", ref="for each row", funcName="request_trigger_after"}
]



methods = [
	"request_list",
	"request_update",
	"request_get_by_id",
	"request_trigger_before",
	"request_trigger_after"
]

alterScripts = [
	"alter table request add column if not exists title CHARACTER VARYING(150);",
	"alter table request add column if not exists system_id int;",
	"alter table request add column if not exists description text;",
	"alter table request add column if not exists state_id int;",
	"alter table request add column if not exists rsk_id int;",
	"alter table request add column if not exists datetime_reciept timestamp;",
	"alter table request add column if not exists how_request_received text;",
	"alter table request add column if not exists customer_id int;",
	"alter table request add column if not exists customer_agent_id int;",
	"alter table request add column if not exists demo_task_id text;",
	"alter table request add column if not exists search_text text;"
]