docType = "Task"
tableComment = "задача"

tableName ="task"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="needs_discussion",					type="bool", 	ext=" default false",	 comment="требует обсуждения"},
	{name="state_id",					type="int", 	ext=" default 1",	 comment="статус"},
	{name="type_id",					type="int",	 comment="тип задачи"},
	{name="system_id",					type="int",	 comment="система"},
	{name="digital_solution_id",					type="int",	 comment="цифровое решение"},
	{name="development_task_id",					type="int",	 comment="задача на разработку"},
	{name="executor_id",					type="int",	 comment="исполнитель"},
	{name="estimate",					type="int",	 comment="оценка"},
	{name="specialist_priority",					type="int",	 comment="приоритет"},
	{name="plan_end_date",					type="timestamp",	 comment="плановая дата завершения"},
	{name="fact_end_date",					type="timestamp",	 comment="фактическая дата завершения"},
	{name="description",					type="text",	 comment="описание"},
	{name="files",					type="jsonb",	 comment="файлы"},
	{name="images",					type="jsonb",	 comment="изображения"},
	{name="process",					type="text",	 comment="процесс"},
	{name="process_files",					type="jsonb",	 comment="файлы результата"},
	{name="process_images",					type="jsonb",	 comment="изображения результата"},
	{name="result",					type="text",	 comment="результат"},
	{name="result_files",					type="jsonb",	 comment="файлы результата"},
	{name="result_images",					type="jsonb",	 comment="изображения результата"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{fld="state_id", ref="ctlg_task_state", fk="id"},
	{fld="type_id", ref="ctlg_task_type", fk="id"},
	{fld="system_id", ref="system", fk="id"},
	{fld="digital_solution_id", ref="digital_solution", fk="id"},
	{fld="development_task_id", ref="development_task", fk="id"},
	{fld="executor_id", ref="man", fk="id"}
]

triggers = [
	{name="task_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="task_trigger_before", when="before insert or update", ref="for each row", funcName="task_trigger_before"},
	{name="task_trigger_after", when="after insert or update", ref="for each row", funcName="task_trigger_after"}
]



methods = [
	"task_get_specialist",
	"task_get_specialist_role",
	"task_list",
	"task_update",
	"task_get_by_id",
	"task_trigger_before",
	"task_trigger_after"
]

alterScripts = [
	"alter table task add column if not exists title CHARACTER VARYING(150);",
	"alter table task add column if not exists needs_discussion bool;",
	"alter table task add column if not exists state_id int;",
	"alter table task add column if not exists type_id int;",
	"alter table task add column if not exists system_id int;",
	"alter table task add column if not exists digital_solution_id int;",
	"alter table task add column if not exists development_task_id int;",
	"alter table task add column if not exists executor_id int;",
	"alter table task add column if not exists estimate int;",
	"alter table task add column if not exists specialist_priority int;",
	"alter table task add column if not exists plan_end_date timestamp;",
	"alter table task add column if not exists fact_end_date timestamp;",
	"alter table task add column if not exists description text;",
	"alter table task add column if not exists files jsonb;",
	"alter table task add column if not exists images jsonb;",
	"alter table task add column if not exists process text;",
	"alter table task add column if not exists process_files jsonb;",
	"alter table task add column if not exists process_images jsonb;",
	"alter table task add column if not exists result text;",
	"alter table task add column if not exists result_files jsonb;",
	"alter table task add column if not exists result_images jsonb;",
	"alter table task add column if not exists search_text text;"
]