docType = "CustomerTaskCustomerAgentLink"
tableComment = "связь задачи заказчика и представителя заказчика"

tableName ="customer_task_customer_agent_link"

fields = [
	{name="id",			type="serial"},
	{name="customer_task_id",					type="int",	 comment="задача заказчика"},
	{name="customer_agent_id",					type="int",	 comment="представитель заказчика"},
	{name="description",					type="text",	 comment="описание"},
	{name="author_id",					type="int",	 comment="автор"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{fld="customer_task_id", ref="customer_task", fk="id"},
	{fld="customer_agent_id", ref="man", fk="id"},
	{fld="author_id", ref="man", fk="id"},
	{name="customer_task_customer_agent_link_already_exist", ext="UNIQUE (customer_task_id, customer_agent_id)"},
]

triggers = [
	{name="customer_task_customer_agent_link_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="customer_task_customer_agent_link_trigger_before", when="before insert or update", ref="for each row", funcName="customer_task_customer_agent_link_trigger_before"},
	{name="customer_task_customer_agent_link_trigger_after", when="after insert or update", ref="for each row", funcName="customer_task_customer_agent_link_trigger_after"}
]



methods = [
	"customer_task_customer_agent_link_get_by_id",
	"customer_task_customer_agent_link_list",
	"customer_task_customer_agent_link_update",
	"customer_task_customer_agent_link_trigger_before",
	"customer_task_customer_agent_link_trigger_after"
]

alterScripts = [
	"alter table customer_task_customer_agent_link add column if not exists customer_task_id int;",
	"alter table customer_task_customer_agent_link add column if not exists customer_agent_id int;",
	"alter table customer_task_customer_agent_link add column if not exists description text;",
	"alter table customer_task_customer_agent_link add column if not exists author_id int;",
	"alter table customer_task_customer_agent_link add column if not exists search_text text;"
]