docType = "CtlgFilter"
tableComment = "фильтр"

tableName ="ctlg_filter"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="user_table_id",					type="int",	 comment="пользователь"},
	{name="index",					type="char",	size=20,	 comment="список"},
	{name="is_default",					type="bool", 	ext=" default false",	 comment="по умолчанию"},
	{name="where_str",					type="text",	 comment="условия фильтра"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="ctlg_filter_title_already_exist", ext="UNIQUE (title)"},
{fld="user_table_id", ref="\"user\"", fk="id"}
]

triggers = [
	{name="ctlg_filter_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="ctlg_filter_trigger_before", when="before insert or update", ref="for each row", funcName="ctlg_filter_trigger_before"},
	{name="ctlg_filter_trigger_after", when="after insert or update", ref="for each row", funcName="ctlg_filter_trigger_after"}
]



methods = [
	"ctlg_filter_list",
	"ctlg_filter_update",
	"ctlg_filter_get_by_id",
	"ctlg_filter_trigger_before",
	"ctlg_filter_trigger_after"
]

alterScripts = [
	"alter table ctlg_filter add column if not exists title CHARACTER VARYING(150);",
	"alter table ctlg_filter add column if not exists user_table_id int;",
	"alter table ctlg_filter add column if not exists index CHARACTER VARYING(20);",
	"alter table ctlg_filter add column if not exists is_default bool;",
	"alter table ctlg_filter add column if not exists where_str text;",
	"alter table ctlg_filter add column if not exists search_text text;"
]