docType = "LegalEntity"
tableComment = "юр.лицо"

tableName ="legal_entity"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="company_id",					type="int",	 comment="компания"},
	{name="description",					type="text",	 comment="описание"},
	{name="requisites",					type="text",	 comment="реквизиты"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="legal_entity_title_already_exist", ext="UNIQUE (title)"},
	{fld="company_id", ref="company", fk="id"}
]

triggers = [
	{name="legal_entity_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="legal_entity_trigger_before", when="before insert or update", ref="for each row", funcName="legal_entity_trigger_before"},
	{name="legal_entity_trigger_after", when="after insert or update", ref="for each row", funcName="legal_entity_trigger_after"}
]



methods = [
	"legal_entity_get_by_id",
	"legal_entity_list",
	"legal_entity_update",
	"legal_entity_trigger_before",
	"legal_entity_trigger_after"
]

alterScripts = [
	"alter table legal_entity add column if not exists title CHARACTER VARYING(150);",
	"alter table legal_entity add column if not exists company_id int;",
	"alter table legal_entity add column if not exists description text;",
	"alter table legal_entity add column if not exists requisites text;",
	"alter table legal_entity add column if not exists search_text text;"
]