docType = "WorkSpecialistLink"
tableComment = "участник дела"

tableName ="work_specialist_link"

fields = [
	{name="id",			type="serial"},
	{name="work_id",					type="int",	 comment="дело"},
	{name="specialist_id",					type="int",	 comment="специалист"},
	{name="description",					type="text",	 comment="описание"},
	{name="author_id",					type="int",	 comment="автор"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{fld="work_id", ref="task", fk="id"},
	{fld="specialist_id", ref="man", fk="id"},
	{fld="author_id", ref="man", fk="id"},
	{name="work_specialist_link_already_exist", ext="UNIQUE (work_id, specialist_id)"},
]

triggers = [
	{name="work_specialist_link_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="work_specialist_link_trigger_before", when="before insert or update", ref="for each row", funcName="work_specialist_link_trigger_before"},
	{name="work_specialist_link_trigger_after", when="after insert or update", ref="for each row", funcName="work_specialist_link_trigger_after"}
]



methods = [
	"work_specialist_link_list",
	"work_specialist_link_update",
	"work_specialist_link_get_by_id",
	"work_specialist_link_trigger_before",
	"work_specialist_link_trigger_after"
]

alterScripts = [
	"alter table work_specialist_link add column if not exists work_id int;",
	"alter table work_specialist_link add column if not exists specialist_id int;",
	"alter table work_specialist_link add column if not exists description text;",
	"alter table work_specialist_link add column if not exists author_id int;",
	"alter table work_specialist_link add column if not exists search_text text;"
]