docType = "CtlgPlanEndDateChangeSide"
tableComment = "из-за кого изменилась плановая дата завершения"

tableName ="ctlg_plan_end_date_change_side"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="ctlg_plan_end_date_change_side_title_already_exist", ext="UNIQUE (title)"}
]

triggers = [
	{name="ctlg_plan_end_date_change_side_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="ctlg_plan_end_date_change_side_trigger_before", when="before insert or update", ref="for each row", funcName="ctlg_plan_end_date_change_side_trigger_before"},
	{name="ctlg_plan_end_date_change_side_trigger_after", when="after insert or update", ref="for each row", funcName="ctlg_plan_end_date_change_side_trigger_after"}
]



methods = [
	"ctlg_plan_end_date_change_side_update",
	"ctlg_plan_end_date_change_side_get_by_id",
	"ctlg_plan_end_date_change_side_list",
	"ctlg_plan_end_date_change_side_trigger_before",
	"ctlg_plan_end_date_change_side_trigger_after"
]

alterScripts = [
	"alter table ctlg_plan_end_date_change_side add column if not exists title CHARACTER VARYING(150);",
	"alter table ctlg_plan_end_date_change_side add column if not exists search_text text;"
]