docType = "DigitalSolution"
tableComment = "цифровое решение"

tableName ="digital_solution"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="state_id",					type="int", 	ext=" default 1",	 comment="статус"},
	{name="system_id",					type="int",	 comment="система"},
	{name="plan_date_end",					type="timestamp",	 comment="планируемая дата завершения"},
	{name="fact_date_end",					type="timestamp",	 comment="фактическая дата завершения"},
	{name="description",					type="text",	 comment="описание"},
	{name="description_files",					type="jsonb",	 comment="файлы описания"},
	{name="description_images",					type="jsonb",	 comment="изображения описания"},
	{name="result",					type="text",	 comment="результат"},
	{name="result_files",					type="jsonb",	 comment="файлы результата"},
	{name="result_images",					type="jsonb",	 comment="изображения результата"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="digital_solution_title_already_exist", ext="UNIQUE (title)"},
	{fld="state_id", ref="ctlg_digital_solution_state", fk="id"},
	{fld="system_id", ref="system", fk="id"}
]

triggers = [
	{name="digital_solution_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="digital_solution_trigger_before", when="before insert or update", ref="for each row", funcName="digital_solution_trigger_before"},
	{name="digital_solution_trigger_after", when="after insert or update", ref="for each row", funcName="digital_solution_trigger_after"}
]



methods = [
	"digital_solution_update",
	"digital_solution_get_by_id",
	"digital_solution_list",
	"digital_solution_trigger_before",
	"digital_solution_trigger_after"
]

alterScripts = [
	"alter table digital_solution add column if not exists title CHARACTER VARYING(150);",
	"alter table digital_solution add column if not exists state_id int;",
	"alter table digital_solution add column if not exists system_id int;",
	"alter table digital_solution add column if not exists plan_date_end timestamp;",
	"alter table digital_solution add column if not exists fact_date_end timestamp;",
	"alter table digital_solution add column if not exists description text;",
	"alter table digital_solution add column if not exists description_files jsonb;",
	"alter table digital_solution add column if not exists description_images jsonb;",
	"alter table digital_solution add column if not exists result text;",
	"alter table digital_solution add column if not exists result_files jsonb;",
	"alter table digital_solution add column if not exists result_images jsonb;",
	"alter table digital_solution add column if not exists search_text text;"
]